[project]
name = "name-generation-mlp-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "notebook>=7.5.1",
    "torch>=2.9.1",
]
